@taskId=8c524299-4385-4dbb-acd6-23ebe7510693
PUT {{host}}/tasks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id":"{{taskId}}",
    "title": "Updated Title",
    "description": "Updated Description",
    "dueDate": "2025-11-20T16:34:09.800Z",
    "isCompleted": true
}
